# @See: https://github.com/ethz-asl/kalibr/wiki/installation
# @See: https://github.com/ctu-mrs/kalibr_docker/blob/master/compose_session/compose.yaml
# `Add VISNAV_WS="YOUR_ROS2/ROS1_PROJECT_PATH" to ~/.bashrc`
services:
  kalibr:
    build:
      context: .
      dockerfile: Dockerfile_ros1_20_04
    tty: true
    volumes:
      -  $VISNAV_WS/bags:/data
      -  $VISNAV_WS/calibration/kalibr-scripts:/scripts
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
    environment:
        DISPLAY: $DISPLAY
        QT_X11_NO_MITSHM: 1
    #command: "tail -f /dev/null"
    #command: bash -c "cd /data && export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1 && echo 500 | rosrun kalibr kalibr_calibrate_cameras --models pinhole-radtan --topics /uav85/camera_front_throttled/image_raw/compressed --target april_6x6.yaml --bag camera_front.bag --bag-freq 5.0"

    # --bag-freq can be used to downsample the camera topic, ideally, to get something like 200 images... otherwise it takes too long to process
    #
    # switch models between pinhole-radtan (for later conversion to camera_calibration result) and pinhole-equi for open vins
    #
    # you can pre-initialize the focal length of the camera by exporting
    #            export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1
    # and then running kalibr with
    #            echo 650 | rosrun kalibr ...
    #command: bash -c "cd /data && export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1 && echo 500 | rosrun kalibr kalibr_calibrate_cameras --models pinhole-radtan --topics /uav85/camera_front_throttled/image_raw/compressed --target april_6x6.yaml --bag camera_front.bag --bag-freq 5.0"
